defaults:
  - encoder: bridge_resnet

_target_: agent.dp_agent.DPAgent
name: dp_agent

planner:
  _target_: networks.diffusion_nets_v2.ConditionalUnet1D
  input_dim: ??? # to be specified later
  global_cond_dim: ??? # to be specified later
  diffusion_step_embed_dim: 256
  down_dims: [256, 512, 1024]
  kernel_size: 5
  n_groups: 8
  downsample: True

# policy input
lowdim_obs: ${data.meta.lowdim_obs}
rgb_obs: ${data.meta.rgb_obs}
obs_normalization: ${data.meta.obs_normalization}
shared_encoder: false

# policy details
obs_horizon: ${obs_horizon}
pred_horizon: ${horizon}
action_horizon: ${action_horizon}
n_diffusion_steps: 100

lr: ${lr}
end_lr: ${end_lr}
warmup_steps: ${warmup_steps}
decay_steps: ${n_grad_steps}
planner_ema_decay: 0.99
encoder_ema_decay: 0.99